//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsignacionCatedratico
    {
        public int idAsignacionCatedratico { get; set; }
        public Nullable<int> idCatedratico { get; set; }
        public int idCurso { get; set; }
        public string Annio { get; set; }
        public string personGroupId { get; set; }
    }
}
