//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsistenciaDetalle
    {
        public int idAsistenciaDetalle { get; set; }
        public int idAsistencia { get; set; }
        public int idEstudiante { get; set; }
        public string Asistencia { get; set; }
    }
}
