//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiante
    {
        public int idEstudiante { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public byte[] Fotografia { get; set; }
        public string Api_Id { get; set; }
        public string personId { get; set; }
    }
}
